src/objects/Debug__c.object
<CustomObject>
    <fields>
        <fullName>BusinessCase__c</fullName>
        <label>BusinessCase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>INFO</fullName>
                </value>
                <value>
                    <fullName>DEBUG</fullName>
                </value>
                <value>
                    <fullName>ERROR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <label>ObjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Debug</label>
    <nameField>
        <label>Debug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Debugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LogUtil.cls
/**
 * Created by sayantan.sb on 18.04.22.
 */

public with sharing class LogUtil {

    public static void insertDebugEvent(String businessCase,String objectName,String objectId,String message,String level){

        try{
            Debug__c debug = new Debug__c();
            debug.BusinessCase__c = businessCase;
            debug.ObjectName__c = objectName;
            debug.ObjectId__c = objectId;
            debug.Message__c = message;
            debug.Level__c = level;

            Database.SaveResult result = Database.insert(debug);
            if(!result.success){
                System.debug('Error in saving Debug object');
            }
        }catch (Exception e){
            System.debug('Error in saving Debug object');
        }

    }

}